ahoyapi: v2
usage: CLI app for development using ahoy.
commands:
  # docker:
  #   usage: A series of docker commands (experimental)
  #   imports:
  #     - .ahoy/docker.ahoy.yml

  pipenv:
    usage: Commands to interact with pipenv
    imports:
      - .ahoy/pipenv.ahoy.yml
