stages:
  - test

.test_template:
  stage: test
  services:
    - name: influxdb:1.8.10
      alias: influxdb
  variables:
    INFLUXDB_HOST: influxdb
    INFLUXDB_PORT: 8086
    INFLUXDB_DB: metrics
    INFLUXDB_USER: admin
    INFLUXDB_USER_PASSWORD: admin123
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry run pytest tests

test:3.10:
  extends: .test_template
  image: python:3.10

test:3.11:
  extends: .test_template
  image: python:3.11

test:3.12:
  extends: .test_template
  image: python:3.12
