image: python:3.9

stages:
  - test

test:
  stage: test
  services:
    - name: influxdb:1.8.10
      alias: influxdb
  variables:
    INFLUXDB_HOST: influxdb
    INFLUXDB_PORT: 8086
    INFLUXDB_DB: metrics
    INFLUXDB_USER: admin
    INFLUXDB_USER_PASSWORD: admin123
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry run nosetests grafane
