---
services:
  metrics:
    image: influxdb:1.8.10
    ports:
      - '8086:8086'
    environment:
      INFLUXDB_DATA_ENGINE: ${INFLUXDB_DATA_ENGINE}
      INFLUXDB_DB: ${INFLUXDB_DB}
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_PASSWORD}

  metrics-v2:
    image: influxdb:2.8
    ports:
      - '8087:8086'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_V2_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_V2_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_V2_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_V2_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_V2_TOKEN}

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      # InfluxDB v1
      INFLUXDB_DB: ${INFLUXDB_DB}
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
      # InfluxDB v2
      INFLUXDB_V2_ORG: ${INFLUXDB_V2_ORG}
      INFLUXDB_V2_BUCKET: ${INFLUXDB_V2_BUCKET}
      INFLUXDB_V2_TOKEN: ${INFLUXDB_V2_TOKEN}
    volumes:
      - ./.docker/grafana/provisioning:/etc/grafana/provisioning
