apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://metrics:8086
    database: ${INFLUXDB_DB}
    user: ${INFLUXDB_USER}
    secureJsonData:
      password: ${INFLUXDB_PASSWORD}
    isDefault: true
